import XCTest
@testable import AISEEBIN

final class VoiceClipsTests: XCTestCase {

    /// The clips folder in the repo, as generated by voice/generate.py.
    private var repoClips: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent().deletingLastPathComponent()
            .appendingPathComponent("voice/clips")
    }

    func testNormaliseFoldsCaseSpacesAndCurlyApostrophes() {
        XCTAssertEqual(VoiceClips.normalise("  I\u{2019}m still   Relocalizing.\n"), "i'm still relocalizing.")
    }

    func testEveryIndexedClipExists() throws {
        let clips = VoiceClips(directory: repoClips)
        XCTAssertGreaterThan(clips.count, 0)
        let url = try XCTUnwrap(clips.url(for: "Relocalizing. Please look around slowly."))
        XCTAssertTrue(FileManager.default.fileExists(atPath: url.path))
    }

    func testPhrasesTheAppBuildsAtRuntimeHaveNoClip() {
        let clips = VoiceClips(directory: repoClips)
        XCTAssertNil(clips.url(for: "You have arrived at the Orchid Display."))
    }

    func testTheSpokenConstantsMatchTheirClips() {
        let clips = VoiceClips(directory: repoClips)
        for text in ["You are off route. Recalculating.",
                     "Tracking lost. Please pause and turn slowly until tracking resumes.",
                     "I'm still relocalizing. Please look around slowly."] {
            XCTAssertNotNil(clips.url(for: text), text)
        }
    }

    func testMissingFolderMeansNoClips() {
        XCTAssertEqual(VoiceClips(directory: nil).count, 0)
        XCTAssertNil(VoiceClips(directory: nil).url(for: "Found you."))
    }
}
