// node --test web/immersal.test.js
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const { parsePLYPoints, identityAlignment, slugFromName, fetchMap } = require('./immersal.js');

function ply(vertices, { colour = true } = {}) {
  const props = ['property float x', 'property float y', 'property float z']
    .concat(colour ? ['property uchar red', 'property uchar green', 'property uchar blue'] : []);
  const header = ['ply', 'format binary_little_endian 1.0', 'comment generated by Immersal Ltd.',
    `element vertex ${vertices.length}`, ...props, 'element face 0', 'property list uchar int vertex_indices', 'end_header', ''].join('\n');
  const stride = colour ? 15 : 12;
  const body = Buffer.alloc(vertices.length * stride);
  vertices.forEach(([x, y, z], i) => {
    body.writeFloatLE(x, i * stride); body.writeFloatLE(y, i * stride + 4); body.writeFloatLE(z, i * stride + 8);
    if (colour) { body[i * stride + 12] = 1; body[i * stride + 13] = 2; body[i * stride + 14] = 3; }
  });
  const buf = Buffer.concat([Buffer.from(header), body]);
  return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.length);
}

test('reads x y z triples and skips colour bytes', () => {
  const pts = parsePLYPoints(ply([[1, 2, 3], [-4.5, 0.25, 9]]));
  assert.deepEqual(Array.from(pts), [1, 2, 3, -4.5, 0.25, 9]);
});

test('works without colour too', () => {
  assert.deepEqual(Array.from(parsePLYPoints(ply([[7, 8, 9]], { colour: false }))), [7, 8, 9]);
});

test('rejects things that are not binary PLY', () => {
  assert.throws(() => parsePLYPoints(new TextEncoder().encode('<!DOCTYPE html>').buffer), /not a PLY/);
  assert.throws(() => parsePLYPoints(new TextEncoder().encode('ply\nformat ascii 1.0\nelement vertex 0\nend_header\n').buffer), /binary/);
});

test('rejects a truncated body', () => {
  const whole = ply([[1, 2, 3], [4, 5, 6]]);
  assert.throws(() => parsePLYPoints(whole.slice(0, whole.byteLength - 4)), /truncated/);
});

test('parses the real Immersal export when it is on disk', { skip: !fs.existsSync(process.env.PLY || '') }, () => {
  const buf = fs.readFileSync(process.env.PLY);
  const pts = parsePLYPoints(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.length));
  assert.equal(pts.length, 5716 * 3);
  // Footprint of the scan, metres, from an independent Python read of the file.
  let minX = Infinity, maxX = -Infinity;
  for (let i = 0; i < pts.length; i += 3) { minX = Math.min(minX, pts[i]); maxX = Math.max(maxX, pts[i]); }
  assert.ok(minX < -19 && minX > -20 && maxX > 4 && maxX < 5, `x range ${minX}..${maxX}`);
});

test('identity alignment names the map and no fitted pairs', () => {
  assert.deepEqual(identityAlignment(151658), { mapIDs: [151658], yaw: 0, tx: 0, tz: 0, pairCount: 0, rmsError: 0 });
});

test('slug rule matches the editor and the app', () => {
  assert.equal(slugFromName('HusselIndoor'), 'husselindoor');
  assert.equal(slugFromName('  Level 2 – East wing '), 'level-2-east-wing');
  assert.equal(slugFromName('***'), '');
});

test('fetchMap surfaces Immersal reasons and refuses unfinished maps', async () => {
  const json = (obj) => ({ ok: true, status: 200, json: async () => obj });
  await assert.rejects(fetchMap({ id: 1, token: 't', fetch: async () => json({ error: 'not found' }) }), /not found under this token/);
  await assert.rejects(fetchMap({ id: 1, token: 't', fetch: async () => json({ error: 'none', status: 'processing' }) }), /not finished/);
  await assert.rejects(fetchMap({ id: 'abc', token: 't', fetch: async () => json({}) }), /positive integer/);
});

test('fetchMap goes through the site proxy when there is no token', async () => {
  const calls = [];
  const fetchImpl = async (url) => { calls.push(url); return { ok: true, status: 200, arrayBuffer: async () => ply([[1, 2, 3]]) }; };
  const map = await fetchMap({ id: 151658, base: '/immersal', fetch: fetchImpl });
  assert.deepEqual(calls, ['/immersal/sparse?id=151658']);
  assert.equal(map.name, 'Immersal 151658');
  assert.deepEqual(Array.from(map.points), [1, 2, 3]);
  await assert.rejects(fetchMap({ id: 1, base: '/immersal', fetch: async () => ({ ok: false, status: 404, statusText: 'Not Found' }) }), /not found under the site's account/);
  await assert.rejects(fetchMap({ id: 1, base: '/immersal', fetch: async () => ({ ok: false, status: 400, statusText: 'Bad Request' }) }), /not found under the site's account/);
  await assert.rejects(fetchMap({ id: 1, fetch: async () => ({}) }), /token or a proxy/);
});

test('fetchMap returns name and points on success', async () => {
  const calls = [];
  const fetchImpl = async (url, opts) => {
    calls.push(url);
    if (url.endsWith('/metadataget')) return { ok: true, json: async () => ({ error: 'none', name: 'HusselIndoor', status: 'done' }) };
    return { ok: true, arrayBuffer: async () => ply([[1, 2, 3]]) };
  };
  const map = await fetchMap({ id: '151658', token: 'tok', fetch: fetchImpl });
  assert.equal(map.name, 'HusselIndoor'); assert.equal(map.id, 151658);
  assert.deepEqual(Array.from(map.points), [1, 2, 3]);
  assert.match(calls[1], /sparse\?token=tok&id=151658$/);
});
